README.md
Let users know that they won't be able to break the README as their changes must be reviewed before publication
=> Expand introduction

README.md
Explicitly specify a closed-access data sources
=> Add prompt for closed-access data

README.md
More user friendly to non-Github users
=> Redo intro to prioritise contact-by-email

README.md
Expand Small Area Statistics so that it is clearer which data link is specified here & edit intro prompting offline data to be added
=> Add UK Smart Meter, Expand SA Stats, Edit Intro

README.md
... https://doi.org/10.1016/j.enbuild.2020.109886
- SEAI Conversion factors
- CIBSE Guide A & F
- Air tightness Ireland & UK
=> Add Ahern's Bottom-up Resid Modelling Sources

README.md
https://doi.org/10.1016/j.apenergy.2020.115834
=> Add sources from Ali et al 2020

.github/ISSUE_TEMPLATE/new-data-source.md
To prompt contributor to follow repo guidelines prior to submitting a PR
=> Add new data source template

.github/ISSUE_TEMPLATE/new-data-source.md
So that prompts won't appear in the contributors PR
=> Hide prompts in new-data-source.md

README.md
=> Add UCD Spatial Data

README.md
So that the README will also track all relevant research
=> Add Publications section

README.md
So could then hyperlink data sources to the relevant research paper
=> Move Publications to top

README.md
as NBERT provides rare detailed hourly Weather, Environment Quality & Energy data at an individual building which may be of interest
=> Add NBERT to Webtools section

README.md
As TABULA contains standardised national-scale archetype information which others may find of use
=> Add TABULA to webtools

README.md
Others may find:
- the BER-map useful to visualize BER data at Small Area level via an interactive webtool.
- the latest EPBD Policy useful as a reference for latest standards & gov-sponsored EPBD reports etc
=> Add BER-map & EPBD Policy link

README.md
Contains climate geodata for Dublin & Cork
Referenced in https://www.researchgate.net/publication/340464701_Generating_Urban-Scale_Building_Data_to_Support_Climate_Modeling
=> Add WUDAPT to Data Repositories

README.md
Was voted on as the preferred publication format
=> Add harvard-reference for publication format

README.md
Contains a lot of information on Dublin infrastructure and good information for DCC on building energy consumption
=> Add smartdublin data portal

.github/workflows/publish.yml
... and not to energy-modelling-ireland.github.io/ireland-energy-wiki
=> Update publish action so publishes to website

.github/workflows/publish.yml, docs/Data-Sources.md
`cd` didn't succeed in changing directory to submodule in the
publish action and so the action failed in trying to push to
the wrong branch
https://github.community/t/use-working-directory-for-entire-job/16747/11
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun
=> Change working dir for deploy action to website submodule

.github/workflows/publish.yml
Inspired by https://github.com/mhausenblas/mkdocs-deploy-gh-pages
=> Publish to website repo by replacing origin

docs/Data-Sources.md, docs/Data-Wishlist.md, docs/Models.md, docs/Tools.md
`mkdocs` requires a 4 space indent to create sub-bullet points
=> BUG: fix indenting in Data Sources

docs/Data-Wishlist.md
So that anyone visiting the website can input
suggestions and vote on data they see as important
=> Add Input & Vote Google Forms to Wishlist

docs/Models.md
Ireland is included in this open EU Transmission
model
=> Add pypsa-eur to models

docs/Data-Wishlist.md
So that voting numbers can be displayed in a column
next to the wishlist entries and thus reordered by
priority
=> Move all data wishlist into a table

.gitmodules, docs/Bios.md
=> Improve Bios layout for mobile view

docs/Bios.md
The markdown badge text was incorrect
=> Update Jason Mc Guire's Bio email

docs/Tools.md
Co-authored-by: olejandro <olejandro@users.noreply.github.com>
=> Add Balmorel & TIMES to Tools

docs/Irish-Models.md, docs/Models.md, docs/Webtools-&-Webmaps.md, docs/index.md
To better differentiate between Tools, Models & Webtools
=> Rename pages Webtools & Models

docs/Data-Sources.md
Highly detailed data on 3-phase LV, MV and HV DSO substation
capacities, locations, loads & remaining capacities
=> Add ESB Availability Capacity Map Data

docs/Data-Wishlist.md
All columns are default equal width which squished the
'Would like...' column on phone view
=> Improve Data-Wishlist.md layout for phones

docs/Data-Wishlist.md
So can prompt contributors to re-vote on new entries
as they are added to the wishlist
=> Add entry date to Date-Wishlist.md

docs/Data-Sources.md
Generates Synthetic data for use in Energy Models
=> Add GlobalEnergyGIS

docs/Data-Sources.md
So it becomes subheader of demand
=> Change Sythetic from h2 to h3

docs/Tools.md
- tableau-public
- Pandas-bokeh
- streamlit
=> Add viz libraries to Tools

docs/Tools.md
Enables easier access to STAC for datasets such as Copernicus
=> Add stactools
